interface Meta {
  title: string;
  description: string;
}

interface MetaPages {
  [key: string]: Meta;
}

export const MetaData: MetaPages = {
  home: {
    title: "Home | Create Next App | NextJs Tailwind StoryBook Scss",
    description:
      "Generated by create next app, NextJs Tailwind StoryBook Scss ",
  },
};
