import React from "react";
import { Story, Meta } from "@storybook/react/types-6-0";

import MetaTags from "./index";
import { StorybookProvider } from "../../storyBookProvider";

export default {
  title: "organisms/MetaTags",
  component: MetaTags,
} as Meta;

export const MetaTagsStory: Story = () => (
  <StorybookProvider>
    <MetaTags
      page="Create Next App"
      description="Generated by create next app"
    />
  </StorybookProvider>
);
