import Head from "next/head";
import React from "react";

interface Props {
  page: string;
  description: string;
}

export default function MetaTags({
  page = "Create Next App",
  description = "Generated by create next app",
}: Props) {
  return (
    <>
      <Head>
        <title>{page}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
